### ISSUE TITLE
Feature Request: Sync namespace with private

### ISSUE THREAD

**Issue by mk-pmb** [JoshuaKGoldberg/eslint-plugin-package-json#1]
Hi! Your plugin looks promising. Could you add these rules to help us keep the namespace and `private` in sync?

* `"private"`property must be either `true` or `false`. (Rule name could be `explicitly-decide-private`)
* If `"private": true` but package name starts with `"@"`: <s>Namespaced package probably should be public!</s> My project had a policy that namespaced package must be public. (Rule name could be `namespaced-requires-public`)
* If `"private": false` but package name doesn't start with `"@"`: Packages must be published in a namespace! (Rule name could be `public-requires-namespaced`)

They should not be auto-fixable, since it's not eslint's job to decide which property is the mistaken one.

**Comment by zetlen** [comment]
Sorry, I'm very late to this one! If this would still be useful to you, I can make it. The rules are mutually exclusive, so I'd do the usual thing where it errors out informatively if there's a conflict. How does that sound?

**Comment by mk-pmb** [comment]
It would indeed be very helpful still. I do not see how these rules might conflict with each other. Could you give an example for that?

**Comment by zetlen** [comment]
@mk-pmb I made one small change: instead of having a specific `explicitly-decide-private` rule, I made a `required-properties` rule that takes an array, to which you can supply `private` along with any other properties you want to require to be explicitly declared. Let me know if #3 works for you!

**Comment by mk-pmb** [comment]
Could you make it a dict instead? That would provide a nice upgrade path for even stricter requirements, like a whitelist of accepted values. (In my case with private, the booleans.)

**Comment by zetlen** [comment]
I agree that it'd be great to validate properties against more complex rules, but I think your latter suggestion is also right that that can be a `valid-properties` rule or something like that.

**Comment by JoshuaKGoldberg** [comment]
> `"private"` property must be either true or false. (Rule name could be `explicitly-decide-private`)

Heh, I would personally want the opposite: not explicitly listing any fields if they're given the default value. Larger config files are harder for contributors to read and can be daunting to newcomers.

Seems like a good idea for a rule, but IMO should be configurable to enforce one way or the other. 

> Namespaced package probably should be public!

Not so. It's common for companies/teams to org-scope their packages and then publish them either on the global npm registry or a private/self-hosted registry.

> If `"private": false` but package name doesn't start with `"@"`: Packages must be published in a namespace! (Rule name could be `public-requires-namespaced`)

What's the root user need here? Is it that a team might want all their packages to always be namespaced?

---

Taking a step back: I _think_ I can imagine scenarios where these privacy rules would be useful, but it's hard to conceptualize. Are there particular reasons you see to use them @mk-pmb / anybody else?

I'm wondering if the potential use cases are so wide that it might make sense to have one or two unified rules that can be configured? That way if other folks have different use cases, they can be captured too. Like how ESLint's [`no-restricted-syntax`](https://eslint.org/docs/latest/rules/no-restricted-syntax) rule is universally useful.

**Comment by mk-pmb** [comment]
@JoshuaKGoldberg

> Not so. It's common for companies/teams to org-scope their packages and then publish them

I'm confused: You seem to start with a contradiction and follow it up with confirmation. I guess it's about the suboptimal word choice of "publish" for that npm action.

> What's the root user need here? Is it that a team might want all their packages to always be namespaced?

Yes, that was the requirement.

> Are there particular reasons you see to use them

Back in the days my reason was company policy.

**Comment by JoshuaKGoldberg** [comment]
> It's common for companies/teams to org-scope their packages and then publish them

I'm also confused now 😄. What are the two statements you see me as having put forward? If it helps, here is a rephrasing what I'm trying to say:

* Scoped and unscoped packages might reasonably be public or private.
    * Some dev groups will intentionally [publish public scoped packages](https://docs.npmjs.com/cli/v10/using-npm/scope#publishing-public-scoped-packages-to-the-primary-npm-registry). Examples: [`@codecademy/gamut`](https://npmjs.com/package/@codecademy/gamut), [`@sentry/node`](https://www.npmjs.com/package/@sentry/node).
    * Some dev groups will intentionally [publish scoped packages as private](https://docs.npmjs.com/cli/v10/using-npm/scope#publishing-private-scoped-packages-to-the-npm-registry). _(I'd post an example, but they're all private!)_
* Scoped and unscoped packages [might be published to any registry](https://docs.npmjs.com/cli/v10/using-npm/scope#associating-a-scope-with-a-registry)
* I don't think there's any single best practice that a built-in rule should always enforce. All of the following possibilities are things different dev groups might want to configure:
    * Whether packages are scoped: some groups always want a scope; some groups want to be un-scoped
    * Whether scoped packages are private: as they might be intentionally publicly available

The only built-in restriction I see as needing to be respected is that _["Private packages always have a scope"](https://docs.npmjs.com/about-private-packages)_. 

> > What's the root user need here? Is it that a team might want all their packages to always be namespaced?
> Yes, that was the requirement, at least for the packages that we would publish.

Maybe there's an opportunity here for additional configuration in this rule, or a separate one: enforcing not just whether a scope exists, but what string(s) it must be if it does?

**Comment by mk-pmb** [comment]
> publish scoped packages as private

That was the feature I wasn't aware of. I thought that npm would NEVER "publish" a package with `private: true`. Now I read your sentence as plain contradiction to my idea that…

> Namespaced package probably should be public

… and I accept your argument. I'll strike that part in the opening post.


> I don't think there's any single best practice that a built-in rule should always enforce.

I agree. None of my suggested rules are meant to be enabled by default.

**Comment by mk-pmb** [comment]
> enforcing not just whether a scope exists, but what string(s) it must be if it does?

Yes, good idea. However, that would open the barrel of how complex a set of rules we want to support for what names are allowed.

**Comment by JoshuaKGoldberg** [comment]
Coming back to this: it's been >12 months and I haven't seen any more requests around this area. I think these rules could be useful but don't think they're common enough to justify adding to `eslint-plugin-package-json` right now. I think for now they'd make more sense as a separate dedicated plugin around package & namespace privacy syncing.

Thanks for filing though - this was an interesting discussion! 🙂
