### ISSUE TITLE
🚀 Feature: Rename valid-package-def to avoid abbreviation

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/eslint-plugin-package-json#132]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I don't like abbreviations in coding. I find it hard to keep track of them. Especially for folk whose first language was not English, they can reduce readability.

The only rule this package contains with an abbreviated name is `valid-package-def`. Let's rename it to ... `valid-package-definition`? `valid-package-schema`? `valid-package-file`? Some bikeshedding

**Comment by michaelfaith** [comment]
I like either `valid-package-definition` or just `valid-package-json`  (since it uses the package.json validator under the covers)

**Comment by JoshuaKGoldberg** [comment]
👍 Agreed, those are both nice. I'm leaning to `valid-package-definition` since JSON is its own permissive standard this happens to be a subset of.
