### ISSUE TITLE
🐛 Bug: Does not detect package.json in Windows environment (again)

### ISSUE THREAD

**Issue by Wondermarin** [JoshuaKGoldberg/eslint-plugin-package-json#142]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

It should work in a Windows environment.

### Actual

Does not work.

### Additional Info

There was already a similar [issue](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues/13) and it was resolved, however, for some reason this does not work in the current version (0.10.1), and there is no fix in the source code.

**Comment by JoshuaKGoldberg** [comment]
Oh for crying out loud... I'd merged #30 into the `master` branch. Not into `main`. _Sigh_.

Thanks for reporting - fixing now...

**Comment by Wondermarin** [comment]
It's working now! Thx.
