### ISSUE TITLE
🚀 Feature: remove order-properties and sort-collections rules from recommended config

### ISSUE THREAD

**Issue by hyoban** [JoshuaKGoldberg/eslint-plugin-package-json#301]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I found that these two rules can be easily [implemented](https://github.com/antfu/eslint-config/blob/d7a157aefd6ded028b92fea7929d1c925dac755c/src/configs/sort.ts#L8-L108) through the `jsonc/sort-keys` rules of the `eslint-plugin-jsonc` plug-in, while order-properties is based on `sort-package-json` and has a bug #80 that is not easy to fix.

Maybe provide a new config preset called `all`.

**Comment by JoshuaKGoldberg** [comment]
> easily [implemented](https://github.com/antfu/eslint-config/blob/d7a157aefd6ded028b92fea7929d1c925dac755c/src/configs/sort.ts#L8-L108) through the jsonc/sort-keys
> easily

That... is not "easily" IMO 😄 asking users to do that is a bit painful.

> a bug https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues/80 that is not easy to fix

Why is that bug not easy to fix?

IMO we should lean towards fixing the bug if possible, rather than weaking what this package is able to do out of the box.

**Comment by hyoban** [comment]
So the question now is how to fix that bug. `order-properties` as described should only sort top-level properties, but using `sort-package-json` to auto-fix will cause sub-keys to be sorted as well.

> It sorts using [sort-object-keys](http://github.com/keithamus/sort-object-keys). It sorts using the well-known keys of a package.json. For the full list check the [default rules](https://github.com/keithamus/sort-package-json/blob/main/defaultRules.md). It sorts sub-keys too - sometimes by a well-known order, other times alphabetically. The initial order was derived from the [package.json docs](https://docs.npmjs.com/files/package.json) with a few extras added for good measure.
> 
> From https://github.com/keithamus/sort-package-json#how-does-it-sort

I'm not sure if we should raise an issue in `sort-package-json` to allow us to control whether sub-keys are sorted or not.

Or we don't use it for auto fix, but just use its recommended sort order.

**Comment by JoshuaKGoldberg** [comment]
> I'm not sure if we should raise an issue in sort-package-json to allow us to control whether sub-keys are sorted or not.

I would think that's the right way to go. The package is actively maintained and I'm sure would love an issue. 🙂 

Closing this out as non-actionable, but please let me know if I'm missing something.
