### ISSUE TITLE
Relicense to MIT

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/eslint-plugin-package-json#34]
Confirmed separately with @zetlen that this is doable & fine. I've been using MIT on most of my other packages and all new ones as a default. 

I believe the only contribution from another human is #6 (cc @sirugh). I believe bumping `disparity` to a newer version should qualify for us not needing to seek relicensing approval (if we did at all?). Bumping the version can't hurt anyway.

**Comment by sirugh** [comment]
🤖
