### ISSUE TITLE
🚀 Feature: (possibly) add eslint-plugin-github-commit-hash

### ISSUE THREAD

**Issue by JustSamuel** [JoshuaKGoldberg/eslint-plugin-package-json#367]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Hey! I learned a lot from this repo regards to making an eslint plugin, and especially one regarding the `package.json`. That is why the general structure of my code should be quite similar and might nicely integrate into the current project. 

I'm not sure if this linting rule is something that fits the package, but since I took quite some inspiration from this repo id seemed fair to mention it here.

**Comment by JoshuaKGoldberg** [comment]
Hey thanks, I'm really happy to hear this repo has helped you learn things! ❤️ 

For https://github.com/JustSamuel/eslint-plugin-github-commit-hash: is there a reason why that's a better practice? I rarely use Git specifiers in `package.json`s myself (and think that most folks don't?) so I'm not familiar with best practices around them.

**Comment by JustSamuel** [comment]
Using Git specifiers is not super common, but not unheard of. For example see [angular-ci](https://github.com/angular/angular-cli/blob/main/package.json), which also uses the commit hash.

The reason why it is a best practice to include the commit hash is that otherwise your dependency would be "unversioned" and `npm i` would download the latest commit.  The `package-lock` also uses the commit hash as a version. 

Linking dependencies via Git is also a nice alternative to npm or to hackily setup private package repo's by putting them on GitHub.

But I do admit that this is a very niche case and might not be super applicable to include in the eslint-plugin.

**Comment by JoshuaKGoldberg** [comment]
Gotcha, thanks for the explanation! Yeah, it's pretty niche - but if it's a universally agreed-upon best practice then maybe it makes sense here? Leaving in `status: in discussion` for a while to see if anybody else has inputs.

**Comment by JustSamuel** [comment]
`yarn` now requires git dependencies to be the tag, branch or the _full 40-characters commit hash_. So if this is incorporated, it would be wise to switch for the shortened 7 I used to the full 40.

**Comment by JoshuaKGoldberg** [comment]
Just following up, it's been about half a year and I haven't heard of any more strong motivations to add this rule. I think for now it's best to treat it as a niche (but still valid!) use case. Closing out for this plugin. 

Thanks for the discussion though! I'm glad https://github.com/JustSamuel/eslint-plugin-github-commit-hash exists for folks that need it. 🙂
