### ISSUE TITLE
New rule: Ensure schema

### ISSUE THREAD

**Issue by Zamiell** [JoshuaKGoldberg/eslint-plugin-package-json#41]
A new rule could be created that ensures a `$schema` field exists inside of the package.json.
Maybe this should be best-practice since it provides tab-complete and validation of fields? Not really sure.

**Comment by Zamiell** [comment]
> Hmm, I don't think I've ever seen a package.json with a @schema or $schema. Are there any projects in the wild using this?

I don't do this is my own projects, so I'm not sure.

> To my knowledge, at least VS Code has good support for package.json autocompletions already.

Oh right, VSCode special-cases any file with the name of "package.json", so this kind of thing would only be helpful if you use `vim` or something like that.

**Comment by JoshuaKGoldberg** [comment]
Got it, thanks. I think this is a pretty niche ask we can close out. If folks start including explicit package schemas in their schemas we can always re-open / recreate.
