### ISSUE TITLE
The recommended config doesn't enable the plugin for you

### ISSUE THREAD

**Issue by Zamiell** [JoshuaKGoldberg/eslint-plugin-package-json#47]
Thus, this makes people consuming the plugin have to add extra boilerplate to their configs.

See e.g. [unicorn's recommended config](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/configs/recommended.js), which is considered best practice AFAIK.

**Comment by JoshuaKGoldberg** [comment]
I like it! Let's tackle this after #40.

**Comment by JoshuaKGoldberg** [comment]
Reflecting on conversation from https://github.com/typescript-eslint/typescript-eslint/issues/8149: I'm not convinced about this as much anymore. I've seen folks have setups that do the "magic" for them, then get confused when things don't work.

Also, the current linked unicorn config (https://github.com/sindresorhus/eslint-plugin-unicorn/blob/331b3068d3c03c6e28a073277f5aa81dc238db3b/configs/recommended.js) just enables rules. Is there a different link we should be looking at?

**Comment by JoshuaKGoldberg** [comment]
This has since been fixed in the new flat config support: #91.


> In your ESLint configuration file:
> 
> ```ts
> import packageJson from "eslint-plugin-package-json/configs/recommended";
> 
> export default [
> 	// your other ESLint configurations
> 	packageJson,
> ];
> ```

Cheers!
