### ISSUE TITLE
🐛 Bug: No way to use in code when using NodeNext resolution

### ISSUE THREAD

**Issue by arietrouw** [JoshuaKGoldberg/eslint-plugin-package-json#497]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

import plugin from 'eslint-plugin-package-json' should return the plugin

### Actual

import { configs, rules } from 'eslint-plugin-package-json' returns {configs, rules}

### Additional Info

The exports from the main/module fields in the root of the package.json export the plugin, but they are not accessible in NodeNext resolutions.

**Comment by JoshuaKGoldberg** [comment]
👋 thanks for trying out the package! I don't know what you mean. "NodeNext" resolution in TypeScript could mean a lot of different package setups. Could you please post an isolated reproduction I can try out?

If it helps: https://antfu.me/posts/why-reproductions-are-required#reproducible-projects-or-playgrounds

**Comment by JoshuaKGoldberg** [comment]
Closing out as non-actionable. Please do post back if you have more details though. Cheers!

**Comment by arietrouw** [comment]
Josh, sorry for the delayed details.  I am using the setting of 'NodeNext' in the resolutions field in my tsconfig.json file.  This causes the loader to use the exports section of the package.json when importing it (vs. the main/modules fields) and the entry points found there seem to be non-functional.

**Comment by arietrouw** [comment]
I will prepare an example for you.
