### ISSUE TITLE
📝 Documentation: `unique-dependencies` description in the README is a copy-paste of `valid-repository-directory`

### ISSUE THREAD

**Issue by zloirock** [JoshuaKGoldberg/eslint-plugin-package-json#529]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Which is definitely incorrect. And there is no documentation for this rule at all.

**Comment by JoshuaKGoldberg** [comment]
Oops. Thanks for the spot 🙂. I think I'd meant to clean this up and never did.
