### ISSUE TITLE
Test failures on main with valid-local-dependency.js

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/eslint-plugin-package-json#60]
If you run `npm test` on the `main` branch, everything passes. ✅ 

But if you specifically run the `valid-local-dependency` rule tests, they fail:

```shell
npx mocha tests/lib/rules/valid-local-dependency.js
```

```plaintext
  10 passing (37ms)
  8 failing
```

Specifically all but the fourth `invalid` cases are failing.

```plaintext
1) valid-local-dependency
       invalid
         {
                        "license": "ISC",
                        "dependencies": {
                            "some-package": "link:./tests/lib/__fixtures__/Valid-local-dependency",
                            "some-other-package": "some-other-package"
                        }
            }:

      AssertionError [ERR_ASSERTION]: Should have 1 error but had 0: []
      + expected - actual

      -0
      +1   
```

FYI @kendallgassner - I had no idea this was a "quirk" when reviewing #11. It's popping up in #35 by virtue of switching to Vitest and all tests now running in CI.

**Comment by JoshuaKGoldberg** [comment]
cc @kendallgassner - I'm curious if this is a Mac-vs-Windows situation (which would explain why the tests would have passed locally when authored, since CI skipped them). I'll have a Windows computer to check next week.

**Comment by kendallgassner** [comment]
@JoshuaKGoldberg this is very possible! I have a MAC and they were definitely passing locally. Sorry for all the trouble.

**Comment by JoshuaKGoldberg** [comment]
No trouble at all 😄 I'm just amused at the tests not being caught until the file is run directly.

**Comment by JoshuaKGoldberg** [comment]
No trouble at all 😄 I'm just amused at the tests not being caught until the file is run directly.

**Comment by JoshuaKGoldberg** [comment]
No trouble at all 😄 I'm just amused at the tests not being caught until the file is run directly.

**Comment by JoshuaKGoldberg** [comment]
No trouble at all 😄 I'm just amused at the tests not being caught until the file is run directly.
