### ISSUE TITLE
📝 Documentation: Do I need to install `jsonc-eslint-parser`?

### ISSUE THREAD

**Issue by rakleed** [JoshuaKGoldberg/eslint-plugin-package-json#601]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I removed `jsonc-eslint-parser`, but ESLint still reports errors in `package.json` and applies autofixes. Do I really need to install `jsonc-eslint-parser`?

And isn't it better to use [`@eslint/json`](https://github.com/eslint/json) for flat config, if it is still needed in some cases?

**Comment by JoshuaKGoldberg** [comment]
👋 Good questions, thanks for posting! 

> Do I really need to install `jsonc-eslint-parser`?

No, that isn't necessary in flat config. I think this is a bug in the docs - the installation command for _[Flat Config](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json?tab=readme-ov-file#flat-config)_ shouldn't include `jsonc-eslint-parser`. Accepting PRs to make separate installation commands for flat & legacy config in the README.md.

> And isn't it better to use [@eslint/json](https://github.com/eslint/json) for flat config, if it is still needed in some cases?

I'm in favor of doing some research there, but don't have the time myself. Also mentioned here: https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues/42#issuecomment-2419932098. If you want to file a new issue & post some initial findings/suggestions, that'd be great, yes please!

**Comment by JoshuaKGoldberg** [comment]
Fixed by #654.
