### ISSUE TITLE
📝 Documentation: More prominently feature contribution guide

### ISSUE THREAD

**Issue by rakleed** [JoshuaKGoldberg/eslint-plugin-package-json#661]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

It would be great to have a contribution guide that includes information on how to test changes and build the plugin. Additionally, it would be helpful to have details about the minimum required Node version and other prerequisites.

**Comment by JoshuaKGoldberg** [comment]
> contribution guide

1. https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/main/.github/CONTRIBUTING.md
2. https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/main/.github/DEVELOPMENT.md

> test changes

https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/main/.github/DEVELOPMENT.md#testing

> build the plugin

https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/main/.github/DEVELOPMENT.md#building

> Minimum required Node version

https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/fbf858b4fb5da133a745dfb32f6d8d7d6a550a4d/package.json#L120-L122

I'm inferring you haven't read through the docs very deeply 🙂. Once you've read through them, if you have any specific questions on things not covered, please do post back or file a new issue.

**Comment by rakleed** [comment]
@JoshuaKGoldberg, for the first time, I discovered the contribution and development guides in the `.github` directory. I’m not sure, but maybe it would be better to place them in the root directory.

And it would be great if you could include a reference to the contribution/development guide in the README file to increase its visibility because it's where I actually search for it.

**Comment by JoshuaKGoldberg** [comment]
I can see why you'd ask for that, but it's a GitHub standard to allow them in `.github`. From https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors (emphasis mine):

> To help your project contributors do good work, you can add a file with contribution guidelines to your project repository's root, `docs`, **or `.github` folder**. When someone opens a pull request or creates an issue, **they will see a link to that file**. The link to the contributing guidelines **also appears on your repository's `contribute` page**. For an example of a contribute page, see [github/docs/contribute](https://github.com/github/docs/contribute).

I think the discoverability issue might be something to take up with the GitHub website itself. I agree that it'd be nice to have more prominent _"hey go read this!"_. 😄

**Comment by rakleed** [comment]
Okay, but it's defenetly worth mentiong contribution guide in the README because almost all open source repositories have them. Here are some examples:

- https://github.com/freeCodeCamp/freeCodeCamp#contributing
- https://github.com/facebook/react#contributing-guide
- https://github.com/vuejs/core#contribution
- https://github.com/ohmyzsh/ohmyzsh#how-do-i-contribute-to-oh-my-zsh
- https://github.com/twbs/bootstrap#contributing
- https://github.com/flutter/flutter#documentation
- https://github.com/microsoft/vscode#contributing
- https://github.com/vercel/next.js#contributing
- https://github.com/golang/go#contributing

**Comment by JoshuaKGoldberg** [comment]
That's a good point. And, in fact, I do this in my other repos - this one just isn't matched to the template!

Example from https://github.com/JoshuaKGoldberg/create-typescript-app?tab=readme-ov-file#development:

> ```md
> ## Development
>
> See [`.github/CONTRIBUTING.md`](./.github/CONTRIBUTING.md), then [`.github/DEVELOPMENT.md`](./.github/DEVELOPMENT.md).
> Thanks! 💖
> ```

Accepting PRs to add the equivalent to this project's README.md. Thanks for filing, good catch!
