### ISSUE TITLE
🛠 Tooling: Use messageId over message

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/eslint-plugin-package-json#81]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

In my experience+opinion it's generally preferable to use [`messageId`](https://eslint.org/docs/latest/extend/custom-rules#messageids)s to specify rule report messages. `message` is mostly for forwarding messages from external tools (example: `valid-package-def`).

This plugin's rules all already use `message`. Let's switch them to `messageId`, when possible.

### Additional Info

See https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/0450e4c8c3251b8149cfe1af6ba5d56ebf8c0e69/docs/rules/prefer-message-ids.md.

**Comment by michaelfaith** [comment]
This https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/pull/708 flagged all the areas that need to be addressed (there were a couple of rules that were already using `messageId`).
